--------------------------------------------------------
--  File created - woensdag-juni-25-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXX_DERIVED_COLUMNS
--------------------------------------------------------
  CREATE TABLE "XXX_DERIVED_COLUMNS" 
   (	"TABLE_OWNER" VARCHAR2(30 CHAR), 
	"TABLE_NAME" VARCHAR2(30 CHAR), 
	"DERIVED_COLUMN" VARCHAR2(30 CHAR), 
	"DERIVATION_ATTRIBUTE" VARCHAR2(30 CHAR), 
	"DERIVATION_OBJ_TYPE" VARCHAR2(30 CHAR), 
	"DERIVATION_METHOD" VARCHAR2(30 CHAR),
	"DERIVATION_ATTRIBUTE_PK_COL" VARCHAR2(30 CHAR),
  "IND_IGNORE_CONSTRUCTOR" VARCHAR2(1 CHAR) DEFAULT 'N',
  "IND_IGNORE_INS" VARCHAR2(1 CHAR) DEFAULT 'N',
	"IND_IGNORE_TO_XML" VARCHAR2(1 CHAR) DEFAULT 'N'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING ;

   COMMENT ON COLUMN "XXX_DERIVED_COLUMNS"."TABLE_OWNER" IS 'Owner of the table';
   COMMENT ON COLUMN "XXX_DERIVED_COLUMNS"."TABLE_NAME" IS 'Table of derived column.';
   COMMENT ON COLUMN "XXX_DERIVED_COLUMNS"."DERIVED_COLUMN" IS 'Column in table tobe derived.';
   COMMENT ON COLUMN "XXX_DERIVED_COLUMNS"."DERIVATION_ATTRIBUTE" IS 'Object type based attribute as input for derivation';
   COMMENT ON COLUMN "XXX_DERIVED_COLUMNS"."DERIVATION_OBJ_TYPE" IS 'Object type with deriviation method.';
   COMMENT ON COLUMN "XXX_DERIVED_COLUMNS"."DERIVATION_METHOD" IS 'Derivation Method';
   COMMENT ON COLUMN "XXX_DERIVED_COLUMNS"."DERIVATION_ATTRIBUTE_PK_COL" IS 'PK Column of derivation attribute.';
   COMMENT ON COLUMN "XXX_DERIVED_COLUMNS"."IND_IGNORE_CONSTRUCTOR" IS 'Indicates if code in constructor should be ignored.';
  COMMENT ON COLUMN "XXX_DERIVED_COLUMNS"."IND_IGNORE_INS" IS 'Indicates if code in ''ins''-method should be ignored.';
	COMMENT ON COLUMN "XXX_DERIVED_COLUMNS"."IND_IGNORE_TO_XML" IS 'Indicates if code in ''to_xml()''-method should be ignored.';
--------------------------------------------------------
--  DDL for Index XXX_DERIVED_COLUMNS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXX_DERIVED_COLUMNS_PK" ON "XXX_DERIVED_COLUMNS" ("TABLE_OWNER", "TABLE_NAME", "DERIVED_COLUMN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255  ;
--------------------------------------------------------
--  Constraints for Table XXX_DERIVED_COLUMNS
--------------------------------------------------------

  ALTER TABLE "XXX_DERIVED_COLUMNS" ADD CONSTRAINT "XXX_DERIVED_COLUMNS_PK" PRIMARY KEY ("TABLE_OWNER", "TABLE_NAME", "DERIVED_COLUMN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255;
  ALTER TABLE "XXX_DERIVED_COLUMNS" ADD CONSTRAINT "XXX_DCN_CHK1" CHECK ("IND_IGNORE_CONSTRUCTOR" in ('Y','N')) ENABLE;
  ALTER TABLE "XXX_DERIVED_COLUMNS" ADD CONSTRAINT "XXX_DCN_CHK2" CHECK ("IND_IGNORE_INS" in ('Y','N')) ENABLE;
  ALTER TABLE "XXX_DERIVED_COLUMNS" ADD CONSTRAINT "XXX_DCN_CHK3" CHECK ("IND_IGNORE_TO_XML" in ('Y','N')) ENABLE;
  ALTER TABLE "XXX_DERIVED_COLUMNS" MODIFY ("IND_IGNORE_CONSTRUCTOR"  NOT NULL ENABLE);
  ALTER TABLE "XXX_DERIVED_COLUMNS" MODIFY ("IND_IGNORE_INS"  NOT NULL ENABLE);
	ALTER TABLE "XXX_DERIVED_COLUMNS" MODIFY ("IND_IGNORE_TO_XML"  NOT NULL ENABLE);
  ALTER TABLE "XXX_DERIVED_COLUMNS" MODIFY ("DERIVATION_OBJ_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXX_DERIVED_COLUMNS" MODIFY ("DERIVATION_ATTRIBUTE" NOT NULL ENABLE);
  ALTER TABLE "XXX_DERIVED_COLUMNS" MODIFY ("DERIVED_COLUMN" NOT NULL ENABLE);
  ALTER TABLE "XXX_DERIVED_COLUMNS" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXX_DERIVED_COLUMNS" MODIFY ("TABLE_OWNER" NOT NULL ENABLE);
