--------------------------------------------------------
--  File created - Monday-October-13-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXX_CUSTOM_METHODS
--------------------------------------------------------

  CREATE TABLE "XXX_CUSTOM_METHODS" 
   (	"TABLE_OWNER" VARCHAR2(30 BYTE), 
	"TABLE_NAME" VARCHAR2(30 BYTE), 
	"TYPE_NAME" VARCHAR2(30 BYTE), 
	"METHOD_NAME" VARCHAR2(30 BYTE), 
        "IND_STATIC"  VARCHAR2(1) DEFAULT 'N', 
        "METHOD_COMMENT" VARCHAR2(4000 CHAR), 
	"METHOD_SPEC" VARCHAR2(4000 CHAR), 
	"METHOD_DECL" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
 LOB ("METHOD_DECL") STORE AS BASICFILE (
  NOCACHE LOGGING 
  ) ;
--------------------------------------------------------
--  DDL for Index XXX_CMD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXX_CMD_PK" ON "XXX_CUSTOM_METHODS" ("TABLE_OWNER", "TABLE_NAME", "TYPE_NAME", "METHOD_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 ;
--------------------------------------------------------
--  Constraints for Table XXX_CUSTOM_METHODS
--------------------------------------------------------

  ALTER TABLE "XXX_CUSTOM_METHODS" ADD CONSTRAINT "XXX_CMD_PK" PRIMARY KEY ("TABLE_OWNER", "TABLE_NAME", "TYPE_NAME", "METHOD_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ENABLE;
  ALTER TABLE "XXX_CUSTOM_METHODS" MODIFY ("METHOD_DECL" NOT NULL ENABLE);
  ALTER TABLE "XXX_CUSTOM_METHODS" MODIFY ("METHOD_SPEC" NOT NULL ENABLE);
  ALTER TABLE "XXX_CUSTOM_METHODS" MODIFY ("METHOD_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXX_CUSTOM_METHODS" MODIFY ("IND_STATIC"  NOT NULL ENABLE);
  ALTER TABLE "XXX_CUSTOM_METHODS" MODIFY ("TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXX_CUSTOM_METHODS" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXX_CUSTOM_METHODS" MODIFY ("TABLE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "XXX_CUSTOM_METHODS" ADD CONSTRAINT XXX_CMD_CHK1 CHECK (IND_STATIC in ('Y','N')) ENABLE;