--------------------------------------------------------
--  File created - donderdag-juni-26-2014   
--------------------------------------------------------
REM INSERTING into XXX_DERIVED_COLUMNS
delete from XXX_DERIVED_COLUMNS;
SET DEFINE OFF;
--Insert into XXX_DERIVED_COLUMNS (TABLE_OWNER,TABLE_NAME,DERIVED_COLUMN,DERIVATION_ATTRIBUTE,DERIVATION_OBJ_TYPE,DERIVATION_METHOD,DERIVATION_ATTRIBUTE_PK_COL,IND_IGNORE_CONSTRUCTOR,IND_IGNORE_INS,IND_IGNORE_TO_XML) values ('DWN','DWN_NATIONALITEIT','NATIONALITEIT_CODE','NATIONALITEIT','DDM_DOMEIN_WAARDEN_TYPE','sel_dom_waarde','WAARDE','N','N','N');

commit;